"""Run the full orchestrator on every persona and write a readable
markdown report to PIPELINE_TEST.md.

Topology per spec line 194: orchestrator → 8 sub-agents (parallel) →
dedup → merge prefs → rubric → filter → final tasks. Trace events are
captured throughout and rendered as a stream below the per-persona
section.
"""

import asyncio
from pathlib import Path

from app import orchestrator
from app.loaders import load_fixture, load_profile
from app.models import OrchestratorResult, ScoredTask


REPO_ROOT = Path(__file__).resolve().parent.parent.parent
OUTPUT_PATH = REPO_ROOT / "PIPELINE_TEST.md"


def _render_scored(s: ScoredTask, indent: str = "") -> str:
    t = s.task
    out = [
        f"{indent}- **[{s.total_score}/7] {t.title}**  *(agent: `{t.sub_agent}`)*\n",
        f"{indent}  - Action: {t.action}\n",
        f"{indent}  - Rationale: {t.rationale}\n",
        f"{indent}  - Surface time: `{t.suggested_surface_time}`\n",
        f"{indent}  - Rubric:\n",
    ]
    for c in s.criteria:
        mark = "✓" if c.matches else "✗"
        out.append(f"{indent}    - {mark} `{c.name}` — {c.reasoning}\n")
    return "".join(out)


def _render_persona(r: OrchestratorResult, mode: str, fixture_summary: str) -> str:
    out: list[str] = []
    out.append(f"\n---\n\n## `{r.persona_slug}`\n\n")
    out.append(
        f"- **Mode:** {mode}\n"
        f"- **Today's slice:** {fixture_summary}\n"
        f"- **Pipeline:** {sum(len(s.tasks) for s in r.sub_agent_results)} candidate tasks "
        f"→ {len(r.scored_tasks)} after dedup → {len(r.final_tasks)} after filter\n"
        f"- **Preference updates:** {len(r.merged_preference_updates)}\n\n"
    )

    # Final emitted tasks (top of section — most important)
    out.append("### Final emitted tasks (post-filter)\n\n")
    if not r.final_tasks:
        out.append("_(none cleared cutoff=4 / per-agent-cap=2 / max=5)_\n")
    else:
        for s in r.final_tasks:
            out.append(_render_scored(s))

    # Dedup decisions
    dedup_events = [e for e in r.trace_events if e.type == "dedup_decision"]
    if dedup_events:
        out.append("\n### Dedup decisions\n\n")
        for ev in dedup_events:
            kept = ev.payload.get("kept", {})
            dropped = ev.payload.get("dropped", [])
            why = ev.payload.get("why", "")
            out.append(
                f"- Kept `{kept.get('sub_agent')}` → \"{kept.get('title')}\"\n"
                f"  - Dropped: "
                + ", ".join(f"`{d.get('sub_agent')}`" for d in dropped)
                + f"\n  - Why: {why}\n"
            )

    # Filtered-out tasks (visibility into what didn't make it)
    filtered = [e for e in r.trace_events if e.type == "task_filtered"]
    if filtered:
        out.append("\n### Filtered out (below cutoff or capped)\n\n")
        for ev in filtered:
            p = ev.payload
            out.append(
                f"- [{p.get('score')}/7] `{p.get('agent')}` — {p.get('title')} ({p.get('reason')})\n"
            )

    # Preference updates merged
    if r.merged_preference_updates:
        out.append("\n### Preference updates merged\n\n")
        for p in r.merged_preference_updates:
            out.append(
                f"- → `{p.section}`: {p.content}\n"
                f"  - Reason: {p.reason}\n"
            )

    # Per-agent raw output (what each agent produced before dedup)
    out.append("\n### Per-agent raw output\n")
    for sar in r.sub_agent_results:
        out.append(
            f"\n#### `{sar.sub_agent}` — {len(sar.tasks)} task(s), "
            f"{len(sar.preference_updates)} pref(s)\n\n"
        )
        if not sar.tasks and not sar.preference_updates:
            out.append("_(silence)_\n")
            continue
        for t in sar.tasks:
            out.append(
                f"- {t.title} *(suggested: `{t.suggested_surface_time}`)*\n"
            )
        for p in sar.preference_updates:
            out.append(f"- _pref_ → `{p.section}`: {p.content[:120]}\n")

    return "".join(out)


async def main() -> None:
    parts: list[str] = []
    parts.append("# Pipeline Test — orchestrator (fan-out → dedup → score → filter)\n\n")
    parts.append(
        "Auto-generated by `backend/scripts/pipeline_test.py`. Each persona is run through "
        "the orchestrator, which fan-outs all 8 sub-agents in parallel, dedupes near-duplicate "
        "tasks across agents, scores survivors via the 7-criterion rubric, and applies the "
        "filter (`cutoff=4`, `per-agent cap=2`, `max=5`).\n"
    )

    for slug in ["aditi", "arjun", "devendra", "meera"]:
        print(f"\n=== {slug} ===", flush=True)
        profile = load_profile(slug)
        di = load_fixture(slug, "2026-05-01")
        mode = "BACKFILL" if di.date == profile.meta.onboarded_at else "STEADY-STATE"
        summary = f"{len(di.gmail)} emails / {len(di.calendar)} events"
        print(f"  [{slug}] running orchestrator...", flush=True)
        result = await orchestrator.run(di, profile)
        print(
            f"  [{slug}] done. "
            f"{sum(len(s.tasks) for s in result.sub_agent_results)} → "
            f"{len(result.scored_tasks)} → {len(result.final_tasks)}",
            flush=True,
        )
        parts.append(_render_persona(result, mode, summary))

    OUTPUT_PATH.write_text("".join(parts))
    print(f"\nwrote {OUTPUT_PATH}")


if __name__ == "__main__":
    asyncio.run(main())
