"""Demo gmail_search, calendar_search and web_search across all personas.

Runs varied per-persona queries that match each persona's actual profile
(Aditi → Meghana's biryani / Karan / BESCOM; Arjun → Flurys / framing /
CESC; etc.) so the output is recognisable, not synthetic.

Writes markdown to TOOL_DEMO.md at the repo root.
"""

import json
from pathlib import Path

from app.tools import make_tools_for_persona, web_search

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
OUTPUT_PATH = REPO_ROOT / "TOOL_DEMO.md"


GMAIL_QUERIES = {
    "aditi":    ["Meghana", "Bali", "Karan", "BESCOM"],
    "arjun":    ["Flurys", "framing", "exhibition", "CESC"],
    "devendra": ["IPL", "Iscon", "Torrent", "AMD"],
    "meera":    ["Zepto", "Airtel", "KEM", "Rahul"],
}

CALENDAR_QUERIES = {
    "aditi":    ["pottery", "Sprint", "Karva", "Bali"],
    "arjun":    [""],
    "devendra": [""],
    "meera":    [""],
}

WEB_QUERIES = {
    "aditi":    "Kendrick Lamar India tour 2026 Bangalore",
    "arjun":    "India Art Fair 2026 Kolkata",
    "devendra": "IPL 2026 final schedule",
    "meera":    "BTS concert India 2026",
}


def _trim(s: str, n: int) -> str:
    s = (s or "").replace("\n", " ").strip()
    return s if len(s) <= n else s[:n].rstrip() + "…"


def render_message(m: dict) -> str:
    return (
        f"- **{m.get('received_at', '')[:10]}** — _{_trim(m.get('from', ''), 50)}_\n"
        f"  - subject: **{_trim(m.get('subject', ''), 80)}**\n"
        f"  - body: {_trim(m.get('body', ''), 140)}\n"
    )


def render_event(e: dict) -> str:
    loc = _trim(e.get("location", "") or "—", 40)
    return f"- **{str(e.get('start', ''))[:16]}** — {_trim(e.get('summary', ''), 60)}  _({loc})_\n"


def render_web_hit(h: dict) -> str:
    title = _trim(h.get("title", ""), 80)
    url = h.get("url", "")
    snippet = _trim(h.get("content", "") or h.get("snippet", ""), 220)
    return f"- **[{title}]({url})**\n  - {snippet}\n"


def main() -> None:
    parts: list[str] = []
    parts.append("# Tool Demo — `gmail_search` · `calendar_search` · `web_search`\n\n")
    parts.append(
        "Auto-generated by `backend/scripts/tool_demo.py`. Each section runs a "
        "few persona-specific queries against each tool and shows the top results.\n"
    )

    for slug in ["aditi", "arjun", "devendra", "meera"]:
        parts.append(f"\n---\n\n## `{slug}`\n")

        tools = make_tools_for_persona(slug)
        gmail_tool, cal_tool, _ = tools

        # gmail_search
        parts.append("\n### `gmail_search`\n")
        for q in GMAIL_QUERIES[slug]:
            results = json.loads(gmail_tool.invoke({"query": q, "max_results": 3}))
            parts.append(f"\n**Query:** `{q}` — {len(results)} match(es), top 3 shown\n\n")
            if not results:
                parts.append("_no results._\n")
            else:
                for m in results:
                    parts.append(render_message(m))

        # calendar_search
        parts.append("\n### `calendar_search`\n")
        for q in CALENDAR_QUERIES[slug]:
            label = q if q else "<all events>"
            results = json.loads(cal_tool.invoke({"query": q, "max_results": 5}))
            parts.append(f"\n**Query:** `{label}` — {len(results)} match(es), top 5 shown\n\n")
            if not results:
                parts.append("_no results (this persona has no calendar)._\n" if not q
                             else "_no results._\n")
            else:
                for e in results:
                    parts.append(render_event(e))

        # web_search
        parts.append("\n### `web_search`\n")
        wq = WEB_QUERIES[slug]
        parts.append(f"\n**Query:** `{wq}`\n\n")
        try:
            raw = web_search.invoke({"query": wq})
            res = json.loads(raw)
            hits = res.get("results", []) if isinstance(res, dict) else []
            parts.append(f"_{len(hits)} hits, top 3 shown_\n\n")
            for h in hits[:3]:
                parts.append(render_web_hit(h))
            if isinstance(res, dict) and res.get("answer"):
                parts.append(f"\n**Tavily answer:** {_trim(res['answer'], 400)}\n")
        except Exception as e:
            parts.append(f"_web_search error: {e}_\n")

    OUTPUT_PATH.write_text("".join(parts))
    print(f"wrote {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
